[package]
name = "proj-crypto"
version = "0.1.0"
authors = ["Tom Eccles"]
description = "Cryptography for my third year project"
licence = "GPL-3"
readme = "todo"
repository = "todo"

[dependencies]
sodiumoxide = "0.0.12"

